// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApZngLaiFE1KQeOHY4RbhH-PZ7dEkjGAg',
    appId: '1:436502697531:web:f95f1375469aa81339ae1e',
    messagingSenderId: '436502697531',
    projectId: 'kccarpoolapp',
    authDomain: 'kccarpoolapp.firebaseapp.com',
    storageBucket: 'kccarpoolapp.firebasestorage.app',
    measurementId: 'G-G5W6901YC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBszmZS4UBFjDslyYjDW7DkXZJ93iEb0vI',
    appId: '1:436502697531:android:b8455351211fb1ac39ae1e',
    messagingSenderId: '436502697531',
    projectId: 'kccarpoolapp',
    storageBucket: 'kccarpoolapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZx_ZmvX86u-Cg2DV1wLQFLjUxDktRaI',
    appId: '1:436502697531:ios:132f95f60b5bad2f39ae1e',
    messagingSenderId: '436502697531',
    projectId: 'kccarpoolapp',
    storageBucket: 'kccarpoolapp.firebasestorage.app',
    iosBundleId: 'com.example.kccarpoolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZx_ZmvX86u-Cg2DV1wLQFLjUxDktRaI',
    appId: '1:436502697531:ios:132f95f60b5bad2f39ae1e',
    messagingSenderId: '436502697531',
    projectId: 'kccarpoolapp',
    storageBucket: 'kccarpoolapp.firebasestorage.app',
    iosBundleId: 'com.example.kccarpoolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZngLaiFE1KQeOHY4RbhH-PZ7dEkjGAg',
    appId: '1:436502697531:web:4dda9b48334a015c39ae1e',
    messagingSenderId: '436502697531',
    projectId: 'kccarpoolapp',
    authDomain: 'kccarpoolapp.firebaseapp.com',
    storageBucket: 'kccarpoolapp.firebasestorage.app',
    measurementId: 'G-E3BTCY35H2',
  );

}